"""Build the analysis arrays for PTB-XL 1.0.3 and reconcile them with Table 1 of the article.

Outputs (data/prep/):
  X100.npy  int16 (N, 1000, 12)  raw ADC units, 1000 units = 1 mV      (records100/)
  X500.npy  int16 (N, 5000, 12)                                         (records500/, --hr)
  meta.parquet   one row per ECG: ids, fold, demographics, quality flags, the 5 superclass
                 labels, 23 subclass labels and 44 diagnostic-statement labels (+ likelihoods)
  label_maps.json  hierarchy statement -> subclass -> superclass

The label construction is the one in the dataset's own example script: every SCP statement
with diagnostic == 1 is mapped to its diagnostic_class, regardless of its likelihood value.
"""
import argparse
import ast
import json
import os
import sys

import warnings

import numpy as np
import pandas as pd

warnings.simplefilter("ignore", pd.errors.PerformanceWarning)
from project_paths import ROOT
RAW = f"{ROOT}/data/ptbxl"
OUT = f"{ROOT}/data/prep"
SUPER = ["NORM", "MI", "STTC", "CD", "HYP"]
LEADS = ["I", "II", "III", "aVR", "aVL", "aVF", "V1", "V2", "V3", "V4", "V5", "V6"]


def read_dat(path, n):
    a = np.fromfile(path, dtype="<i2")
    assert a.size == n * 12, (path, a.size)
    return a.reshape(n, 12)


def check_header(path, n, fs):
    """Every header must declare 12 signals, format 16, gain 1000/mV, baseline 0, lead order."""
    L = open(path).read().strip().split("\n")
    h = L[0].split()
    assert int(h[1]) == 12 and int(h[2]) == fs and int(h[3]) == n, (path, L[0])
    for k, line in enumerate(L[1:13]):
        p = line.split()
        assert p[1] == "16" and p[2].startswith("1000.0(0)/mV"), (path, line)
        assert p[-1].upper() == LEADS[k].upper(), (path, line)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--hr", action="store_true", help="also build X500.npy")
    ap.add_argument("--meta_only", action="store_true")
    ap.add_argument("--only_hr", action="store_true")
    a = ap.parse_args()
    os.makedirs(OUT, exist_ok=True)
    db = pd.read_csv(f"{RAW}/ptbxl_database.csv", index_col="ecg_id")
    db["scp"] = db.scp_codes.apply(ast.literal_eval)
    st = pd.read_csv(f"{RAW}/scp_statements.csv", index_col=0)
    dg = st[st.diagnostic == 1]
    stmts = list(dg.index)                                   # 44 diagnostic statements
    subs = sorted(dg.diagnostic_subclass.unique())           # 23 subclasses
    sub_of = dg.diagnostic_subclass.to_dict()
    sup_of = dg.diagnostic_class.to_dict()
    sub_sup = {s: dg[dg.diagnostic_subclass == s].diagnostic_class.iloc[0] for s in subs}
    assert all(dg[dg.diagnostic_subclass == s].diagnostic_class.nunique() == 1 for s in subs)

    N = len(db)
    Y5 = np.zeros((N, 5), np.int8)
    Ysub = np.zeros((N, len(subs)), np.int8)
    Yst = np.zeros((N, len(stmts)), np.int8)
    Lst = np.full((N, len(stmts)), np.nan, np.float32)        # likelihood of each statement
    for i, d in enumerate(db.scp):
        for code, lik in d.items():
            if code in sup_of:
                Y5[i, SUPER.index(sup_of[code])] = 1
                Ysub[i, subs.index(sub_of[code])] = 1
                Yst[i, stmts.index(code)] = 1
                Lst[i, stmts.index(code)] = lik
    meta = db[["patient_id", "age", "sex", "height", "weight", "nurse", "site", "device",
               "recording_date", "validated_by_human", "second_opinion",
               "initial_autogenerated_report", "strat_fold", "filename_lr", "filename_hr",
               "heart_axis"]].copy()
    for c in ["baseline_drift", "static_noise", "burst_noise", "electrodes_problems",
              "extra_beats", "pacemaker"]:
        meta["q_" + c] = db[c].notna().astype(np.int8).values
    for j, s in enumerate(SUPER):
        meta["y_" + s] = Y5[:, j]
    for j, s in enumerate(subs):
        meta["sub_" + s] = Ysub[:, j]
    for j, s in enumerate(stmts):
        meta["st_" + s] = Yst[:, j]
        meta["lik_" + s] = Lst[:, j]
    meta["n_super"] = Y5.sum(1)
    meta["split"] = np.where(meta.strat_fold <= 8, "train",
                             np.where(meta.strat_fold == 9, "val", "test"))
    meta = meta.reset_index()
    meta.to_parquet(f"{OUT}/meta.parquet")
    json.dump(dict(super=SUPER, subs=subs, stmts=stmts, sub_of=sub_of, sup_of=sup_of,
                   sub_sup=sub_sup, leads=LEADS), open(f"{OUT}/label_maps.json", "w"), indent=1)
    print("records", N, "patients", meta.patient_id.nunique(),
          "with >=1 superclass", int((meta.n_super > 0).sum()))

    if a.meta_only:
        return 0
    for fs, n, col, name, on in ((100, 1000, "filename_lr", "X100", not a.only_hr),
                                 (500, 5000, "filename_hr", "X500", a.hr or a.only_hr)):
        if not on:
            continue
        X = np.lib.format.open_memmap(f"{OUT}/{name}.npy.part", "w+", np.int16, (N, n, 12))
        for i, f in enumerate(meta[col]):
            if i % 2000 == 0:
                check_header(f"{RAW}/{f}.hea", n, fs)
                print(name, i, flush=True)
            X[i] = read_dat(f"{RAW}/{f}.dat", n)
        X.flush()
        del X
        os.replace(f"{OUT}/{name}.npy.part", f"{OUT}/{name}.npy")
        X = np.load(f"{OUT}/{name}.npy", mmap_mode="r")
        print(name, X.shape, "abs max (mV)", float(np.abs(X[::50]).max()) / 1000)
    return 0


if __name__ == "__main__":
    sys.exit(main())
